# Generated by Django 5.1.7 on 2025-03-17 14:13

from django.db import migrations

def insert_holidays(apps, schema_editor):
    TimeSlot = apps.get_model('timeschedulingweb', 'TimeSlot')
    TimeSlot(start_time = '2025-05-01T00:00:00',
             end_time = '2025-05-01T23:59:59',
             description = 'Labour Time').save()
    TimeSlot(start_time = '2025-08-15T00:00:00',
             end_time = '2025-08-15T23:59:59',
             description = 'Independence Day').save()
    TimeSlot(start_time = '2025-05-01T00:00:00',
             end_time = '2025-06-30T23:59:59',
             description = 'Summer Holidays').save()

class Migration(migrations.Migration):

    dependencies = [
        ('timeschedulingweb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_holidays)
    ]
